let all=[],range="today",previousRange="today",selectedCats=new Set(),left=300,firstLoad=true,audioOn=localStorage.getItem("mamakAudio")==="1";
const $=s=>document.querySelector(s);
const cats=["Tümü","Cinayet","İntihar","Terör","Asayiş","Kavga","Trafik Kazası","Taciz","Silahlı Olay","Düğünde Silah","Hırsızlık","Dolandırıcılık","Uyuşturucu","Kayıp Kişi","Yangın","Sağlık","Yol","Altyapı","Diğer"];
$("#cats").innerHTML=cats.map((x,i)=>`<button class="${i?"":"active"}" data-cat="${x}">${x}</button>`).join("");
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function inRange(e){const d=new Date(e.published),now=new Date();if(range==="last24")return now-d<=86400000;if(range==="today")return d.toDateString()===now.toDateString();if(range==="yesterday"){const y=new Date(now);y.setDate(y.getDate()-1);return d.toDateString()===y.toDateString()}return now-d<=Number(range)*60000}
function catClass(x){const m={"Cinayet":"critical","Terör":"critical","Silahlı Olay":"critical","Düğünde Silah":"critical","Taciz":"purple","İntihar":"purple","Kavga":"orange","Trafik Kazası":"orange","Yangın":"orange","Uyuşturucu":"blue","Hırsızlık":"blue","Dolandırıcılık":"blue","Asayiş":"blue","Kayıp Kişi":"yellow"};return m[x]||"gray"}
function render(){const q=$("#query").value.toLocaleLowerCase("tr"),now=Date.now();const base=all.filter(e=>inRange(e)&&(`${e.title} ${e.location} ${e.summary}`.toLocaleLowerCase("tr").includes(q)));const list=base.filter(e=>{if(!selectedCats.size)return true;const labels=e.categories&&e.categories.length?e.categories:[e.category];return labels.some(x=>selectedCats.has(x))});const last24=all.filter(e=>now-new Date(e.published).getTime()<=86400000).length;$("#last24Count").textContent=last24;$("#last24").classList.toggle("active",range==="last24");$("#count").textContent=list.length+" olay";$("#cats").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x.dataset.cat==="Tümü"?!selectedCats.size:selectedCats.has(x.dataset.cat)));const counts={};base.forEach(e=>(e.categories&&e.categories.length?e.categories:[e.category]).forEach(x=>counts[x]=(counts[x]||0)+1));const ranked=Object.entries(counts).sort((a,b)=>b[1]-a[1]),max=ranked[0]?.[1]||1;$("#statsTotal").textContent=base.length;$("#statsTitle").textContent=(range==="last24"?"Son 24 Saat":document.querySelector("#ranges .active")?.textContent||"Seçili dönem")+" olay dağılımı";$("#statBars").innerHTML=ranked.length?ranked.map(([k,v])=>`<button class="stat-row ${selectedCats.has(k)?"selected":""}" data-stat-cat="${esc(k)}" title="${esc(k)} olaylarını seç"><span>${esc(k)}</span><div><i class="${catClass(k)}" style="width:${Math.max(6,v/max*100)}%"></i></div><b>${v}</b></button>`).join(""):'<p class="meta">Bu aralıkta istatistik oluşturacak olay yok.</p>';$("#events").innerHTML=list.length?list.map(e=>{const labels=e.categories&&e.categories.length?e.categories:[e.category],platform=e.platform||"Haber";return `<section class="card"><div class="icon">${esc(e.icon)}</div><div><div class="card-top"><span class="tag ${e.confidence>=80?"high":""}">${esc(e.status)} • %${e.confidence}</span><div class="category-badges">${labels.map(x=>`<span class="cat-badge ${catClass(x)}">${esc(x)}</span>`).join("")}</div></div><h2>${esc(e.title)}</h2><div class="meta">📍 ${esc(e.location)} · 📅 ${new Date(e.published).toLocaleDateString("tr-TR")} · 🕐 ${new Date(e.published).toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"})} · ${e.sources||1} kaynak · ${esc(platform)}</div><p>${esc(e.summary)}</p><a href="${esc(e.url)}" target="_blank" rel="noopener">Kaynağı aç → <strong>${esc(platform)}</strong></a></div></section>`}).join(""):'<div class="empty"><h2>Uygun olay bulunamadı</h2><p>Seçilen filtrelere uyan kayıt yok.</p></div>'}
function beep(){try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.type="sine";o.frequency.setValueAtTime(880,a.currentTime);o.frequency.setValueAtTime(660,a.currentTime+.22);g.gain.setValueAtTime(.22,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.7);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.7)}catch{}}
function soundLabel(){$("#sound").textContent=audioOn?"🔊 Ses Açık":"🔇 Sesi Aç";$("#sound").classList.toggle("sound-on",audioOn)}
async function load(){left=300;try{const r=await fetch("data/events.json?"+Date.now()),d=await r.json(),incoming=d.events||[];const old=new Set(all.map(e=>e.url||e.title));const fresh=incoming.filter(e=>!old.has(e.url||e.title));all=incoming;$("#last").textContent=new Date(d.updated_at).toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("#notice").innerHTML=d.error?'<div class="notice">'+esc(d.error)+'</div>':fresh.length&&!firstLoad?'<div class="notice new">🚨 '+fresh.length+' yeni olay bulundu.</div>':"";if(audioOn&&fresh.length&&!firstLoad)beep();firstLoad=false;render()}catch{$("#notice").innerHTML='<div class="notice">Veri dosyasına ulaşılamadı. Biraz sonra tekrar deneyin.</div>'}}
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.id==="last24"){if(range==="last24"){range=previousRange}else{previousRange=range;range="last24"}$("#ranges").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x.dataset.range===range));render();setTimeout(()=>$("#events").scrollIntoView({behavior:"smooth",block:"start"}),50);return}if(b.dataset.statCat){selectedCats.has(b.dataset.statCat)?selectedCats.delete(b.dataset.statCat):selectedCats.add(b.dataset.statCat);render();setTimeout(()=>$("#events").scrollIntoView({behavior:"smooth",block:"start"}),50);return}if(b.dataset.range){range=b.dataset.range;previousRange=range;$("#ranges").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));render()}if(b.dataset.cat){if(b.dataset.cat==="Tümü")selectedCats.clear();else selectedCats.has(b.dataset.cat)?selectedCats.delete(b.dataset.cat):selectedCats.add(b.dataset.cat);render()}});
$("#sound").onclick=()=>{audioOn=!audioOn;localStorage.setItem("mamakAudio",audioOn?"1":"0");soundLabel();if(audioOn)beep()};
$("#query").addEventListener("input",render);$("#refresh").onclick=load;
setInterval(()=>{left--;if(left<=0)load();$("#next").textContent=String(Math.floor(left/60)).padStart(2,"0")+":"+String(left%60).padStart(2,"0")},1000);
soundLabel();load();