let all=[],range="today",previousRange="today",selectedCats=new Set(),left=300,firstLoad=true,map,markerLayer,currentById=new Map();
let audioOn=localStorage.getItem("mamakAudio")==="1";
let splitEvents=new Set(JSON.parse(localStorage.getItem("mamakSplitEvents")||"[]"));
let notifyPrefs=Object.assign({confidence:60,sound:true,browser:false,categories:["Cinayet","Terör","Silahlı Olay","Düğünde Silah","Yangın","Trafik Kazası"]},JSON.parse(localStorage.getItem("mamakNotifyPrefs")||"{}"));
const $=s=>document.querySelector(s);
const cats=["Tümü","Cinayet","İntihar","Terör","Asayiş","Kavga","Trafik Kazası","Taciz","Silahlı Olay","Düğünde Silah","Hırsızlık","Dolandırıcılık","Uyuşturucu","Kayıp Kişi","Yangın","Sağlık","Yol","Altyapı","Diğer"];
$("#cats").innerHTML=cats.map((x,i)=>`<button class="${i?"":"active"}" data-cat="${x}">${x}</button>`).join("");
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function keyOf(e){return e._parentKey||e.url||e.title}
function labelsOf(e){return e.categories&&e.categories.length?e.categories:[e.category]}
function inRange(e){const d=new Date(e.published),now=new Date();if(range==="last24")return now-d<=86400000;if(range==="today")return d.toDateString()===now.toDateString();if(range==="yesterday"){const y=new Date(now);y.setDate(y.getDate()-1);return d.toDateString()===y.toDateString()}return now-d<=Number(range)*60000}
function catClass(x){const m={"Cinayet":"critical","Terör":"critical","Silahlı Olay":"critical","Düğünde Silah":"critical","Taciz":"purple","İntihar":"purple","Kavga":"orange","Trafik Kazası":"orange","Yangın":"orange","Uyuşturucu":"blue","Hırsızlık":"blue","Dolandırıcılık":"blue","Asayiş":"blue","Kayıp Kişi":"yellow"};return m[x]||"gray"}
function catColor(x){return catClass(x)==="critical"?"#ef4444":catClass(x)==="purple"?"#a855f7":catClass(x)==="orange"?"#f97316":catClass(x)==="blue"?"#2563eb":catClass(x)==="yellow"?"#eab308":"#64748b"}
function expandedEvents(){const out=[];all.forEach(e=>{const k=keyOf(e),links=e.source_links||[];if(splitEvents.has(k)&&links.length>1){links.forEach((x,i)=>out.push(Object.assign({},e,{title:x.title||e.title,url:x.url||e.url,platform:x.platform||e.platform,published:x.published||e.published,sources:1,source_links:[x],summary:"Bu kaynak, yanlış birleşim düzeltmesiyle bu cihazda ayrı gösteriliyor.",_parentKey:k,_splitIndex:i}))) }else out.push(e)});return out}
function previousCount(events){const now=new Date(),end=now.getTime();let start,prevStart,prevEnd;if(range==="today"){start=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime();prevEnd=start;prevStart=start-86400000}else if(range==="yesterday"){prevEnd=new Date(now.getFullYear(),now.getMonth(),now.getDate()-1).getTime();start=prevEnd;prevStart=start-86400000}else{const mins=range==="last24"?1440:Number(range);if(!mins)return null;start=end-mins*60000;prevEnd=start;prevStart=start-mins*60000}return events.filter(e=>{const t=new Date(e.published).getTime();return t>=prevStart&&t<prevEnd}).length}
function updateMap(list){if(!window.L)return;if(!map){map=L.map("map",{scrollWheelZoom:false}).setView([39.9308,32.9307],12);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"© OpenStreetMap"}).addTo(map);markerLayer=L.layerGroup().addTo(map)}markerLayer.clearLayers();const bounds=[];list.forEach(e=>{const lat=Number(e.lat),lon=Number(e.lon);if(!lat||!lon)return;const id=e._uiId,color=catColor(labelsOf(e)[0]);const m=L.circleMarker([lat,lon],{radius:e.location_precision==="mahalle"?8:5,color,fillColor:color,fillOpacity:e.location_precision==="mahalle"?.85:.35,weight:2}).addTo(markerLayer);m.bindTooltip(`<b>${esc(labelsOf(e)[0])}</b><br>${esc(e.neighborhood||"Mamak Geneli")}<br>${esc(e.title).slice(0,90)}`);m.on("click",()=>openDetail(id));bounds.push([lat,lon])});$("#mapCount").textContent=bounds.length+" işaret";if(bounds.length)map.fitBounds(bounds,{padding:[25,25],maxZoom:14});setTimeout(()=>map.invalidateSize(),50)}
function render(){const q=$("#query").value.toLocaleLowerCase("tr"),now=Date.now(),visible=expandedEvents();const base=visible.filter(e=>inRange(e)&&(`${e.title} ${e.location} ${e.neighborhood} ${e.summary}`.toLocaleLowerCase("tr").includes(q)));const list=base.filter(e=>!selectedCats.size||labelsOf(e).some(x=>selectedCats.has(x)));currentById.clear();list.forEach((e,i)=>{e._uiId="event-"+i;currentById.set(e._uiId,e)});
 const last24=visible.filter(e=>now-new Date(e.published).getTime()<=86400000).length;$("#last24Count").textContent=last24;$("#last24").classList.toggle("active",range==="last24");$("#count").textContent=list.length+" benzersiz olay";$("#cats").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x.dataset.cat==="Tümü"?!selectedCats.size:selectedCats.has(x.dataset.cat)));
 const counts={};base.forEach(e=>[...new Set(labelsOf(e))].forEach(x=>counts[x]=(counts[x]||0)+1));const ranked=Object.entries(counts).sort((a,b)=>b[1]-a[1]),max=ranked[0]?.[1]||1;$("#statsTotal").textContent=base.length;$("#statsTitle").textContent=(range==="last24"?"Son 24 Saat":document.querySelector("#ranges .active")?.textContent||"Seçili dönem")+" benzersiz olay dağılımı";
 const prev=previousCount(visible),diff=prev==null?null:base.length-prev,merged=base.filter(e=>(e.sources||1)>1).length,sourceTotal=base.reduce((n,e)=>n+(e.sources||1),0),hood={};base.forEach(e=>hood[e.neighborhood||"Mamak Geneli"]=(hood[e.neighborhood||"Mamak Geneli"]||0)+1);const topHood=Object.entries(hood).sort((a,b)=>b[1]-a[1])[0];
 $("#statExtras").innerHTML=`<div><b>${sourceTotal}</b><span>Kaynak kaydı</span></div><div><b>${merged}</b><span>Birleşik olay</span></div><div><b>${diff==null?"—":(diff>0?"+":"")+diff}</b><span>Önceki döneme fark</span></div><div><b>${esc(topHood?.[0]||"—")}</b><span>En yoğun mahalle</span></div>`;
 $("#statBars").innerHTML=ranked.length?ranked.map(([k,v])=>`<button class="stat-row ${selectedCats.has(k)?"selected":""}" data-stat-cat="${esc(k)}"><span>${esc(k)}</span><div><i class="${catClass(k)}" style="width:${Math.max(6,v/max*100)}%"></i></div><b>${v}</b></button>`).join(""):'<p class="meta">Bu aralıkta istatistik oluşturacak olay yok.</p>';
 $("#events").innerHTML=list.length?list.map(e=>{const labels=labelsOf(e),platform=e.platform||"Haber";return `<section class="card"><div class="icon">${esc(e.icon)}</div><div><div class="card-top"><span class="tag ${e.confidence>=80?"high":""}">${esc(e.status)} • %${e.confidence}</span><div class="category-badges">${labels.map(x=>`<span class="cat-badge ${catClass(x)}">${esc(x)}</span>`).join("")}</div></div><h2>${esc(e.title)}</h2><div class="meta">📍 ${esc(e.location)} · 📅 ${new Date(e.published).toLocaleDateString("tr-TR")} · 🕐 ${new Date(e.published).toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"})} · ${e.sources||1} kaynak · ${esc(platform)}</div><p>${esc(e.summary)}</p><div class="card-actions"><button data-detail="${e._uiId}">Olay ayrıntısı</button><a href="${esc(e.url)}" target="_blank" rel="noopener">Kaynağı aç → <strong>${esc(platform)}</strong></a></div></div></section>`}).join(""):'<div class="empty"><h2>Uygun olay bulunamadı</h2><p>Seçilen filtrelere uyan kayıt yok.</p></div>';updateMap(list)}
function phaseFor(title,i,total){const t=String(title).toLocaleLowerCase("tr");if(/tutuk|yakalan|gözalt/.test(t))return"Şüpheli yakalandı / adli süreç";if(/söndür|kontrol alt/.test(t))return"Olay kontrol altına alındı";if(/müdahale|ekip/.test(t))return"Ekipler müdahale ediyor";if(/yaralı|ambulans/.test(t))return"Sağlık müdahalesi bildirildi";return i===0?"İlk açık kaynak bildirimi":i===total-1?"Son kaynak güncellemesi":"Yeni kaynak eklendi"}
function openDetail(id){const e=currentById.get(id);if(!e)return;const links=(e.source_links&&e.source_links.length?e.source_links:[{platform:e.platform,title:e.title,url:e.url,published:e.published}]).slice().sort((a,b)=>new Date(a.published||e.published)-new Date(b.published||e.published));const parentKey=keyOf(e),isSplit=splitEvents.has(parentKey);$("#detailContent").innerHTML=`<div class="detail-head"><div class="icon">${esc(e.icon)}</div><div><div class="category-badges">${labelsOf(e).map(x=>`<span class="cat-badge ${catClass(x)}">${esc(x)}</span>`).join("")}</div><h2>${esc(e.title)}</h2><p class="meta">📍 ${esc(e.location)} · ${e.sources||1} kaynak · Güven %${e.confidence}</p></div></div><h3>Olayın gelişimi</h3><ol class="timeline">${links.map((x,i)=>`<li><b>${phaseFor(x.title,i,links.length)}</b><span>${new Date(x.published||e.published).toLocaleString("tr-TR")} · ${esc(x.platform||"Haber")}</span><p>${esc(x.title||e.title)}</p></li>`).join("")}</ol><h3>Kaynaklar</h3><div class="source-list">${links.map((x,i)=>`<a href="${esc(x.url||e.url)}" target="_blank" rel="noopener"><b>${i+1}. ${esc(x.platform||"Haber")}</b><span>${esc(x.title||e.title)}</span></a>`).join("")}</div>${links.length>1||isSplit?`<button class="split-button" data-split="${esc(parentKey)}">${isSplit?"Bu cihazda yeniden birleştir":"Yanlış birleşim: Bu cihazda ayır"}</button>`:""}<p class="local-note">Ayırma düzeltmesi yalnızca bu tarayıcıda saklanır.</p>`;$("#detailModal").showModal()}
function shouldNotify(e){return Number(e.confidence||0)>=Number(notifyPrefs.confidence)&&labelsOf(e).some(c=>notifyPrefs.categories.includes(c))}
function beep(){try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.type="sine";o.frequency.setValueAtTime(880,a.currentTime);o.frequency.setValueAtTime(660,a.currentTime+.22);g.gain.setValueAtTime(.22,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.7);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.7)}catch{}}
function notifyNew(events){const chosen=events.filter(shouldNotify);if(!chosen.length)return;if(notifyPrefs.sound&&audioOn)beep();if(notifyPrefs.browser&&Notification.permission==="granted"){const e=chosen[0];new Notification("Mamak'ta yeni olay",{body:labelsOf(e).join(", ")+" — "+e.title,tag:keyOf(e)})}}
function soundLabel(){$("#sound").textContent=audioOn?"🔊 Ses Açık":"🔇 Sesi Aç";$("#sound").classList.toggle("sound-on",audioOn)}
function openNotify(){const box=$("#notifyCats");box.innerHTML=cats.slice(1).map(c=>`<label class="check"><input type="checkbox" value="${esc(c)}" ${notifyPrefs.categories.includes(c)?"checked":""}> ${esc(c)}</label>`).join("");$("#notifyConfidence").value=String(notifyPrefs.confidence);$("#notifySound").checked=notifyPrefs.sound;$("#notifyBrowser").checked=notifyPrefs.browser;$("#notifyModal").showModal()}
async function saveNotify(){notifyPrefs={confidence:Number($("#notifyConfidence").value),sound:$("#notifySound").checked,browser:$("#notifyBrowser").checked,categories:[...$("#notifyCats").querySelectorAll("input:checked")].map(x=>x.value)};if(notifyPrefs.browser&&"Notification"in window&&Notification.permission==="default")await Notification.requestPermission();localStorage.setItem("mamakNotifyPrefs",JSON.stringify(notifyPrefs));$("#notifyModal").close();$("#notice").innerHTML='<div class="notice new">Akıllı bildirim ayarları kaydedildi.</div>'}
async function load(){left=300;try{const r=await fetch("data/events.json?"+Date.now()),d=await r.json(),incoming=d.events||[];const old=new Set(all.map(e=>e.url||e.title));const fresh=incoming.filter(e=>!old.has(e.url||e.title));all=incoming;$("#last").textContent=new Date(d.updated_at).toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"});$("#notice").innerHTML=d.error?'<div class="notice">'+esc(d.error)+'</div>':fresh.length&&!firstLoad?'<div class="notice new">🚨 '+fresh.length+' yeni benzersiz olay bulundu.</div>':"";if(fresh.length&&!firstLoad)notifyNew(fresh);firstLoad=false;render()}catch{$("#notice").innerHTML='<div class="notice">Veri dosyasına ulaşılamadı. Biraz sonra tekrar deneyin.</div>'}}
document.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.close){$("#"+b.dataset.close).close();return}if(b.dataset.detail){openDetail(b.dataset.detail);return}if(b.dataset.split){splitEvents.has(b.dataset.split)?splitEvents.delete(b.dataset.split):splitEvents.add(b.dataset.split);localStorage.setItem("mamakSplitEvents",JSON.stringify([...splitEvents]));$("#detailModal").close();render();return}if(b.id==="notifySettings"){openNotify();return}if(b.id==="saveNotify"){saveNotify();return}if(b.id==="homeTitle"){location.reload();return}if(b.id==="last24"){if(range==="last24")range=previousRange;else{previousRange=range;range="last24"}$("#ranges").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x.dataset.range===range));render();setTimeout(()=>$("#events").scrollIntoView({behavior:"smooth",block:"start"}),50);return}if(b.dataset.statCat){selectedCats.has(b.dataset.statCat)?selectedCats.delete(b.dataset.statCat):selectedCats.add(b.dataset.statCat);render();setTimeout(()=>$("#events").scrollIntoView({behavior:"smooth",block:"start"}),50);return}if(b.dataset.range){range=b.dataset.range;previousRange=range;$("#ranges").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));render()}if(b.dataset.cat){if(b.dataset.cat==="Tümü")selectedCats.clear();else selectedCats.has(b.dataset.cat)?selectedCats.delete(b.dataset.cat):selectedCats.add(b.dataset.cat);render()}});
$("#sound").onclick=()=>{audioOn=!audioOn;localStorage.setItem("mamakAudio",audioOn?"1":"0");soundLabel();if(audioOn)beep()};
$("#query").addEventListener("input",render);$("#refresh").onclick=load;
setInterval(()=>{left--;if(left<=0)load();$("#next").textContent=String(Math.floor(left/60)).padStart(2,"0")+":"+String(left%60).padStart(2,"0")},1000);
soundLabel();load();